#api_app_homepage:
    #path:     /
    #defaults: { _controller: APIAppBundle:Default:index }
    #type: rest

api_app_user:
    resource: APIAppBundle\Controller\UserController
    type: rest
    prefix: /user